# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20160701_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
