# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160702_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('BOY', '\u041c\u0430\u043b\u044c\u0447\u0438\u043a'), ('GIRL', '\u0414\u0435\u0432\u043e\u0447\u043a\u0430'), ('UNI', '\u0423\u043d\u0438\u0441\u0435\u043a\u0441')], default='BOY', max_length=4),
        ),
    ]
