# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160705_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='title',
        ),
    ]
