# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='tracking_id',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
